services:
  mysql:
    image: mysql:8.1
    container_name: mysql-database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --event-scheduler=ON
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  mysql_data:
